{frame: [[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,
        0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0,
        0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]],
    [[0, 0, 0], [0, 0, 0], [57, 28, 28], [130, 65, 65], [126, 63, 63], [28, 14, 14],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [57, 28, 28], [130, 65, 65], [126,
        63, 63], [28, 14, 14], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [111, 55, 55], [
        251, 126, 126], [205, 103, 103], [215, 108, 108], [245, 123, 123], [57, 28,
        28], [0, 0, 0], [0, 0, 0], [111, 55, 55], [251, 126, 126], [205, 103, 103],
      [215, 108, 108], [245, 123, 123], [57, 28, 28], [0, 0, 0]], [[6, 3, 3], [237,
        119, 119], [118, 59, 59], [0, 0, 0], [0, 0, 0], [177, 89, 89], [174, 87, 87],
      [0, 0, 0], [6, 3, 3], [237, 119, 119], [118, 59, 59], [0, 0, 0], [0, 0, 0],
      [177, 89, 89], [174, 87, 87], [0, 0, 0]], [[4, 2, 2], [102, 51, 51], [24, 12,
        12], [0, 0, 0], [0, 0, 0], [179, 90, 90], [167, 83, 83], [0, 0, 0], [4, 2,
        2], [102, 51, 51], [24, 12, 12], [0, 0, 0], [0, 0, 0], [179, 90, 90], [167,
        83, 83], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [66, 33,
        33], [248, 125, 125], [52, 26, 26], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,
        0], [0, 0, 0], [66, 33, 33], [248, 125, 125], [52, 26, 26], [0, 0, 0]], [
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [25, 13, 13], [229, 115, 115], [128, 64, 64],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [25, 13, 13], [229, 115,
        115], [128, 64, 64], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [16, 8,
        8], [210, 106, 106], [156, 78, 78], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,
        0], [0, 0, 0], [16, 8, 8], [210, 106, 106], [156, 78, 78], [0, 0, 0], [0,
        0, 0], [0, 0, 0]], [[0, 0, 0], [7, 4, 4], [192, 96, 96], [176, 88, 88], [
        3, 1, 1], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [7, 4, 4], [192, 96,
        96], [176, 88, 88], [3, 1, 1], [0, 0, 0], [0, 0, 0], [0, 0, 0]], [[4, 2, 2],
      [173, 87, 87], [250, 126, 126], [139, 69, 69], [130, 65, 65], [130, 65, 65],
      [122, 61, 61], [9, 5, 5], [4, 2, 2], [173, 87, 87], [250, 126, 126], [139, 69,
        69], [130, 65, 65], [130, 65, 65], [122, 61, 61], [9, 5, 5]], [[60, 30, 30],
      [208, 104, 104], [206, 103, 103], [206, 103, 103], [206, 103, 103], [206, 103,
        103], [200, 100, 100], [24, 12, 12], [60, 30, 30], [208, 104, 104], [206,
        103, 103], [206, 103, 103], [206, 103, 103], [206, 103, 103], [200, 100, 100],
      [24, 12, 12]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,
        0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0,
        0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0]]], image_name: number_22.png}
