{frame: [[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,
        0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0,
        0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]],
    [[0, 0, 0], [0, 0, 0], [0, 0, 0], [19, 10, 10], [69, 34, 34], [0, 0, 0], [0, 0,
        0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [3, 1, 1], [95,
        47, 47], [1, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [23, 12, 12], [198,
        99, 99], [185, 93, 93], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,
        0], [0, 0, 0], [0, 0, 0], [100, 50, 50], [235, 118, 118], [2, 1, 1], [0, 0,
        0]], [[0, 0, 0], [42, 21, 21], [242, 122, 122], [249, 125, 125], [180, 90,
        90], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [32,
        16, 16], [241, 121, 121], [229, 115, 115], [0, 0, 0], [0, 0, 0]], [[0, 0,
        0], [11, 5, 5], [77, 38, 38], [136, 68, 68], [180, 90, 90], [0, 0, 0], [0,
        0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [2, 1, 1], [192, 96, 96], [231, 116,
        116], [229, 115, 115], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0,
        0], [135, 68, 68], [180, 90, 90], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,
        0], [0, 0, 0], [114, 58, 58], [229, 115, 115], [107, 53, 53], [229, 115, 115],
      [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [135, 68, 68], [180,
        90, 90], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [43, 22, 22], [247, 124,
        124], [70, 35, 35], [89, 44, 44], [229, 115, 115], [0, 0, 0], [0, 0, 0]],
    [[0, 0, 0], [0, 0, 0], [0, 0, 0], [135, 68, 68], [180, 90, 90], [0, 0, 0], [0,
        0, 0], [0, 0, 0], [6, 3, 3], [206, 103, 103], [224, 113, 113], [130, 65, 65],
      [174, 87, 87], [242, 122, 122], [130, 65, 65], [50, 25, 25]], [[0, 0, 0], [
        0, 0, 0], [0, 0, 0], [135, 68, 68], [180, 90, 90], [0, 0, 0], [0, 0, 0], [
        0, 0, 0], [53, 27, 27], [204, 102, 102], [204, 102, 102], [204, 102, 102],
      [222, 111, 111], [250, 125, 125], [204, 102, 102], [94, 47, 47]], [[0, 0, 0],
      [0, 0, 0], [0, 0, 0], [135, 68, 68], [180, 90, 90], [0, 0, 0], [0, 0, 0], [
        0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [89, 44, 44], [229,
        115, 115], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [97, 48,
        48], [137, 68, 68], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [62, 31, 31], [177, 88, 88], [0, 0, 0], [0, 0, 0]], [
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]], image_name: number_14.png}
