{frame: [[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,
        0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0,
        0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]],
    [[0, 0, 0], [0, 0, 0], [0, 0, 0], [19, 10, 10], [69, 34, 34], [0, 0, 0], [0, 0,
        0], [0, 0, 0], [0, 0, 0], [4, 2, 2], [76, 38, 38], [130, 65, 65], [127, 63,
        63], [49, 25, 25], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [23, 12,
        12], [198, 99, 99], [185, 93, 93], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,
        0], [171, 85, 85], [245, 123, 123], [205, 103, 103], [210, 106, 106], [252,
        127, 127], [108, 54, 54], [0, 0, 0]], [[0, 0, 0], [42, 21, 21], [242, 122,
        122], [249, 125, 125], [180, 90, 90], [0, 0, 0], [0, 0, 0], [0, 0, 0], [6,
        3, 3], [247, 124, 124], [93, 46, 46], [0, 0, 0], [0, 0, 0], [154, 78, 78],
      [190, 95, 95], [0, 0, 0]], [[0, 0, 0], [11, 5, 5], [77, 38, 38], [136, 68, 68],
      [180, 90, 90], [0, 0, 0], [0, 0, 0], [0, 0, 0], [2, 1, 1], [197, 99, 99], [
        189, 95, 95], [47, 23, 23], [66, 33, 33], [227, 114, 114], [136, 68, 68],
      [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [135, 68, 68], [180, 90, 90],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [58, 29, 29], [253, 127, 127], [
        255, 128, 128], [255, 128, 128], [233, 117, 117], [14, 7, 7], [0, 0, 0]],
    [[0, 0, 0], [0, 0, 0], [0, 0, 0], [135, 68, 68], [180, 90, 90], [0, 0, 0], [0,
        0, 0], [0, 0, 0], [6, 3, 3], [204, 103, 103], [201, 101, 101], [89, 45, 45],
      [107, 53, 53], [230, 115, 115], [147, 74, 74], [0, 0, 0]], [[0, 0, 0], [0, 0,
        0], [0, 0, 0], [135, 68, 68], [180, 90, 90], [0, 0, 0], [0, 0, 0], [0, 0,
        0], [85, 42, 42], [248, 124, 124], [20, 10, 10], [0, 0, 0], [0, 0, 0], [76,
        38, 38], [251, 126, 126], [25, 12, 12]], [[0, 0, 0], [0, 0, 0], [0, 0, 0],
      [135, 68, 68], [180, 90, 90], [0, 0, 0], [0, 0, 0], [0, 0, 0], [97, 48, 48],
      [240, 120, 120], [3, 1, 1], [0, 0, 0], [0, 0, 0], [51, 25, 25], [255, 128, 128],
      [33, 17, 17]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [135, 68, 68], [180, 90, 90],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [26, 13, 13], [249, 125, 125], [186, 93, 93],
      [130, 65, 65], [132, 66, 66], [215, 108, 108], [209, 105, 105], [2, 1, 1]],
    [[0, 0, 0], [0, 0, 0], [0, 0, 0], [97, 48, 48], [137, 68, 68], [0, 0, 0], [0,
        0, 0], [0, 0, 0], [0, 0, 0], [57, 28, 28], [160, 81, 81], [206, 103, 103],
      [203, 102, 102], [139, 70, 70], [30, 15, 15], [0, 0, 0]], [[0, 0, 0], [0, 0,
        0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0,
        0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [
        0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,
        0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0,
        0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]], image_name: number_18.png}
