{frame: [[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,
        0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0,
        0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]],
    [[0, 0, 0], [0, 0, 0], [0, 0, 0], [19, 10, 10], [69, 34, 34], [0, 0, 0], [0, 0,
        0], [0, 0, 0], [0, 0, 0], [64, 32, 32], [130, 65, 65], [130, 65, 65], [130,
        65, 65], [130, 65, 65], [27, 14, 14], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [
        23, 12, 12], [198, 99, 99], [185, 93, 93], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [161, 80, 80], [236, 119, 119], [204, 102, 102], [204, 102, 102],
      [203, 102, 102], [58, 29, 29], [0, 0, 0]], [[0, 0, 0], [42, 21, 21], [242, 122,
        122], [249, 125, 125], [180, 90, 90], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0,
        0, 0], [184, 92, 92], [138, 69, 69], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0,
        0, 0], [0, 0, 0]], [[0, 0, 0], [11, 5, 5], [77, 38, 38], [136, 68, 68], [
        180, 90, 90], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [211, 106, 106],
      [193, 97, 97], [170, 85, 85], [155, 78, 78], [65, 32, 32], [0, 0, 0], [0, 0,
        0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [135, 68, 68], [180, 90, 90], [0, 0,
        0], [0, 0, 0], [0, 0, 0], [5, 2, 2], [232, 116, 116], [196, 98, 98], [154,
        77, 77], [188, 94, 94], [254, 127, 127], [104, 52, 52], [0, 0, 0]], [[0, 0,
        0], [0, 0, 0], [0, 0, 0], [135, 68, 68], [180, 90, 90], [0, 0, 0], [0, 0,
        0], [0, 0, 0], [0, 0, 0], [3, 2, 2], [0, 0, 0], [0, 0, 0], [0, 0, 0], [124,
        62, 62], [228, 114, 114], [3, 2, 2]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [
        135, 68, 68], [180, 90, 90], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [
        0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [54, 27, 27], [255, 128, 128],
      [38, 19, 19]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [135, 68, 68], [180, 90, 90],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [52, 26, 26], [164, 82, 82], [4, 2, 2], [0,
        0, 0], [0, 0, 0], [102, 51, 51], [236, 118, 118], [12, 6, 6]], [[0, 0, 0],
      [0, 0, 0], [0, 0, 0], [135, 68, 68], [180, 90, 90], [0, 0, 0], [0, 0, 0], [
        0, 0, 0], [26, 13, 13], [249, 125, 125], [186, 93, 93], [130, 65, 65], [149,
        75, 75], [247, 124, 124], [132, 66, 66], [0, 0, 0]], [[0, 0, 0], [0, 0, 0],
      [0, 0, 0], [97, 48, 48], [137, 68, 68], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0,
        0, 0], [57, 28, 28], [160, 81, 81], [206, 103, 103], [187, 94, 94], [102,
        51, 51], [1, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]],
    [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0]]], image_name: number_15.png}
