{frame: [[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,
        0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0,
        0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]],
    [[0, 0, 0], [0, 0, 0], [0, 0, 0], [19, 10, 10], [69, 34, 34], [0, 0, 0], [0, 0,
        0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [37, 18, 18], [120, 60, 60], [70, 35,
        35], [2, 1, 1], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [23, 12, 12],
      [198, 99, 99], [185, 93, 93], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [
        116, 58, 58], [255, 128, 128], [217, 109, 109], [249, 125, 125], [190, 95,
        95], [15, 8, 8], [0, 0, 0]], [[0, 0, 0], [42, 21, 21], [242, 122, 122], [
        249, 125, 125], [180, 90, 90], [0, 0, 0], [0, 0, 0], [0, 0, 0], [27, 13, 13],
      [253, 127, 127], [101, 50, 50], [0, 0, 0], [31, 16, 16], [236, 118, 118], [
        107, 53, 53], [0, 0, 0]], [[0, 0, 0], [11, 5, 5], [77, 38, 38], [136, 68,
        68], [180, 90, 90], [0, 0, 0], [0, 0, 0], [0, 0, 0], [100, 50, 50], [251,
        126, 126], [5, 2, 2], [0, 0, 0], [0, 0, 0], [176, 88, 88], [172, 86, 86],
      [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [135, 68, 68], [180, 90, 90],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [36, 18, 18], [254, 127, 127], [68, 34, 34],
      [0, 0, 0], [12, 6, 6], [223, 112, 112], [180, 90, 90], [0, 0, 0]], [[0, 0, 0],
      [0, 0, 0], [0, 0, 0], [135, 68, 68], [180, 90, 90], [0, 0, 0], [0, 0, 0], [
        0, 0, 0], [2, 1, 1], [154, 77, 77], [250, 125, 125], [190, 95, 95], [230,
        116, 116], [255, 128, 128], [188, 94, 94], [0, 0, 0]], [[0, 0, 0], [0, 0,
        0], [0, 0, 0], [135, 68, 68], [180, 90, 90], [0, 0, 0], [0, 0, 0], [0, 0,
        0], [0, 0, 0], [5, 2, 2], [79, 39, 39], [157, 79, 79], [109, 55, 55], [198,
        99, 99], [143, 72, 72], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [135,
        68, 68], [180, 90, 90], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [50, 25,
        25], [9, 4, 4], [0, 0, 0], [8, 4, 4], [237, 119, 119], [99, 49, 49], [0, 0,
        0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [135, 68, 68], [180, 90, 90], [0, 0,
        0], [0, 0, 0], [0, 0, 0], [3, 1, 1], [214, 107, 107], [192, 96, 96], [130,
        65, 65], [189, 95, 95], [218, 109, 109], [13, 6, 6], [0, 0, 0]], [[0, 0, 0],
      [0, 0, 0], [0, 0, 0], [97, 48, 48], [137, 68, 68], [0, 0, 0], [0, 0, 0], [0,
        0, 0], [0, 0, 0], [56, 28, 28], [161, 81, 81], [206, 103, 103], [157, 79,
        79], [51, 25, 25], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
      [0, 0, 0], [0, 0, 0], [0, 0, 0]]], image_name: number_19.png}
